title:MASTER_X_PORTFOLIO
author: Hazemk537
email: hazemk537@gmail.com
description: > # this is hazem shehawy portfolio "baseurl:"
 hello

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: jekyll-theme-cayman
show_excerpts: true # set to false to remove excerpts on the homepage
